# Generated by Django 5.0.2 on 2024-02-28 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LessonModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="lesson name")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "LessonModel",
                "verbose_name_plural": "LessonModels",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UnitModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="unit name")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lesson.lessonmodel",
                        verbose_name="Lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "UnitModel",
                "verbose_name_plural": "UnitModels",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WordModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=128, verbose_name="word")),
                (
                    "part_of_speech",
                    models.CharField(max_length=50, verbose_name="part of speech"),
                ),
                ("definition", models.TextField(verbose_name="definition")),
                ("examples", models.TextField(verbose_name="examples")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="word_images/", verbose_name="image"
                    ),
                ),
                (
                    "adjective",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="adjective"
                    ),
                ),
                (
                    "noun",
                    models.CharField(blank=True, max_length=50, verbose_name="noun"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lesson.unitmodel",
                        verbose_name="",
                    ),
                ),
            ],
            options={
                "verbose_name": "WordModel",
                "verbose_name_plural": "WordModels",
                "ordering": ["-created_at"],
            },
        ),
    ]
