# Generated by Django 5.0.2 on 2024-03-06 21:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lesson", "0002_coursemodel_unitmodel_audio_unitmodel_description_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CourseModel",
            new_name="LessonModel",
        ),
        migrations.AlterModelOptions(
            name="lessonmodel",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "LessonModel",
                "verbose_name_plural": "LessonModels",
            },
        ),
    ]
