# Generated by Django 5.0.2 on 2024-04-19 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_rename_coursemodel_lessonmodel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LessonModel',
            new_name='CourseModel',
        ),
        migrations.AlterModelOptions(
            name='coursemodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'CourseModel', 'verbose_name_plural': 'CourseModels'},
        ),
    ]
