# Generated by Django 5.0.2 on 2024-04-19 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_rename_lessonmodel_coursemodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitmodel',
            old_name='lesson',
            new_name='course',
        ),
    ]
