# Generated by Django 5.0.2 on 2024-05-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_rename_lesson_unitmodel_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitmodel',
            options={'ordering': ['-order', '-created_at'], 'verbose_name': 'UnitModel', 'verbose_name_plural': 'UnitModels'},
        ),
        migrations.AddField(
            model_name='unitmodel',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='order'),
        ),
    ]
