# Generated by Django 5.0.2 on 2024-05-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0007_unitmodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='course_images/', verbose_name='image'),
        ),
    ]
