# Generated by Django 5.0.2 on 2024-02-28 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("lesson", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStudyWordModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "right_count",
                    models.PositiveIntegerField(default=0, verbose_name="right count"),
                ),
                (
                    "wrong_count",
                    models.PositiveIntegerField(default=0, verbose_name="wrong count"),
                ),
                ("note", models.TextField(blank=True, verbose_name="note")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lesson.wordmodel",
                        verbose_name="word",
                    ),
                ),
            ],
            options={
                "verbose_name": "UserStudyWordModel",
                "verbose_name_plural": "UserStudyWordModels",
                "ordering": ["-created_at"],
            },
        ),
    ]
