# Generated by Django 5.0.2 on 2024-04-30 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_rename_lesson_unitmodel_course'),
        ('my_user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userstudywordmodel',
            name='progress_step',
            field=models.IntegerField(default=0, verbose_name='study type progress'),
        ),
        migrations.AddField(
            model_name='userstudywordmodel',
            name='study_type',
            field=models.CharField(choices=[('intro', 'intro'), ('card', 'card'), ('listening', 'listening'), ('writing', 'writing')], default='intro', max_length=64, verbose_name='study type'),
        ),
        migrations.CreateModel(
            name='UserStudySessionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_correct', models.PositiveIntegerField(default=15, verbose_name='max correct')),
                ('max_session', models.PositiveIntegerField(default=30, verbose_name='max session')),
                ('correct', models.PositiveIntegerField(default=0, verbose_name='correct')),
                ('incorrect', models.PositiveIntegerField(default=0, verbose_name='incorrect')),
                ('current', models.PositiveIntegerField(default=0, verbose_name='current')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('word', models.ManyToManyField(to='lesson.wordmodel', verbose_name='words studied in the session')),
            ],
            options={
                'verbose_name': 'UserStudySessionModel',
                'verbose_name_plural': 'UserStudySessionModels',
                'ordering': ['-created_at'],
            },
        ),
    ]
