# Generated by Django 5.0.2 on 2024-05-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_user', '0002_userstudywordmodel_progress_step_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstudysessionmodel',
            old_name='word',
            new_name='words',
        ),
        migrations.AddField(
            model_name='userstudysessionmodel',
            name='learn_id',
            field=models.PositiveIntegerField(default=1, verbose_name='learn id'),
        ),
    ]
