# Generated by Django 5.0.2 on 2024-05-09 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0008_coursemodel_image'),
        ('my_user', '0003_rename_word_userstudysessionmodel_words_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstudysessionmodel',
            name='max_correct',
            field=models.PositiveIntegerField(default=10, verbose_name='max correct'),
        ),
        migrations.CreateModel(
            name='UserEnrollCourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.coursemodel', verbose_name='course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'UserEnrollCourseModel',
                'verbose_name_plural': 'UserEnrollCourseModels',
                'ordering': ['-created_at'],
            },
        ),
    ]
